
spring:
  application:
    name: northwind.backend

  datasource:
    url: jdbc:postgresql://localhost:5432/northwind
    username: northwind
    password: northwind
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8765
